##Spring Configuration
server:
  port: 8080
  servlet:
    context-path: /alphanumeric-key
spring:
  application:
    name: poc-alphanumeric-key
  main:
    web-application-type: reactive
  sleuth:
    propagation:
      type: aws
    reactor:
      instrumentation-type: decorate_queues
  webflux:
    base-path: /alphanumeric-key
